### ISSUE TITLE
Cannot install it from n8n itself

### ISSUE THREAD

**Issue by cmmata** [digital-boss/n8n-nodes-zabbix#2]
I tried to install this node from n8n itself, but it says it cannot find the package. I think it's because in npm website, the package lacks the `n8n-community-node-package` tag. Can it be? Could you add it to simplify the installation, or is there any impediment to install it from there?

Thanks in advance.

**Comment by tony-cp** [comment]
You can install it from n8n by using "@digital-boss/n8n-nodes-zabbix" instead of just n8n-nodes-zabbix.

**Comment by cmmata** [comment]
It works with that name. Thank you!
